# Generated by Django 2.1 on 2018-09-09 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('received_amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('balance', models.DecimalField(decimal_places=4, max_digits=20)),
                ('rs_in_words', models.CharField(blank=True, max_length=200, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.Client')),
            ],
        ),
        migrations.CreateModel(
            name='BillDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('no_of_sessions', models.IntegerField(blank=True, null=True)),
                ('package_amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('bill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bill.Bill')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_of_payment', models.CharField(max_length=30)),
                ('card_no', models.CharField(blank=True, max_length=16, null=True)),
                ('date_of_payment', models.DateField()),
                ('approval_code', models.CharField(blank=True, max_length=100, null=True)),
                ('cheque_no', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('booking_done_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='payment_details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bill.PaymentDetails'),
        ),
    ]
