# Generated by Django 2.1 on 2018-11-08 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='payment_details',
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='bill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bill.Bill'),
        ),
    ]
