# Generated by Django 2.1 on 2018-12-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_auto_20181108_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billdescription',
            name='no_of_sessions',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
